# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.6.5'

gem 'httparty'
gem 'json'
gem 'sinatra'

group :development do
  gem 'shotgun'
end

group :test do
  gem 'rspec'
  gem 'webmock'
end
